### PR TITLE
fix: add cache clean

### PR DESCRIPTION
**Pull request by ggera**
## fixes NO TICKET 
[docs deployment](https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/d3oeht7cvddn19/master/108?step=BUILD) is failing throwing the following error
```
at Generator.next (<anonymous>)
                                 Error: [BABEL] /codebuild/output/src443175444/src/docs/docs/develop/07_dApp/02_well-known-did-config.md: Cannot find module '@babel/helper-get-function-arity'
                                 Require stack:
                                 - /codebuild/output/src443175444/src/docs/node_modules/remark-mdx/node_modules/@babel/helper-function-name/lib/index.js
```

### CODE REVIEW

**Comment by ntn-x2** [comment]
Is it a definite fix or do we need to merge-and-see?

**Comment by ggera** [comment]
> Is it a definite fix or do we need to merge-and-see?

Kinda merge & see yet I sawthis  [similar issue](https://github.com/babel/babel/discussions/14069) that gets fixed via cache clean

**Comment by ntn-x2** [comment]
I would pull @rflechtner in on this, if he has some time.

**Review by ntn-x2 — APPROVED** [review]
Ok we need the fix to be in place, so let's see if this works.

**Pull request merged**
