### PR TITLE
messagingfix

### PR DESCRIPTION
**Pull request by aybarsayan**
## fixes KILTProtocol/ticket#312
Please include a summary of the changes provided with this pull request and which issue has been fixed. 
Please also provide some context if necessary.

## How to test:
Please provide a brief step-by-step instruction.
If necessary provide information about dependencies (specific configuration, branches, database dumps, etc.)

- Step 1
- Step 2
- etc.

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)
    * Either PR or Ticket to update [the Docs](https://github.com/KILTprotocol/docs)
    * Link the PR/Ticket here

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
@aybarsayan Could you explain the changes? I'm not completely sure why all the hash and address changes are needed.

**Comment by aybarsayan** [comment]
Hi Cris,

I've made a single change in the document, specifically correcting a broken
link. The line previously reading "[messaging
protocol](../../../../concepts/07_messaging.md)" has now been updated to
"messaging protocol."

I also noticed that some hashes appear to have changed automatically. This
might be due to my local build, but I'm not entirely certain. Please note
that these changes were not made intentionally.

Best regards,


18 Oca 2024 Per 11:26 tarihinde Chris Chinchilla ***@***.***>
şunu yazdı:

**Comment by ChrisChinchilla** [comment]
@aybarsayan Hmm, the link wasn't broken, but two different links, though I am actually not sure if that was useful anyway. The other files are a result of local builds and to be honest, should probably be added to .gitignore anyway. I can tidy this up and get it merged if you like, I also think the branch name should be changed as it's a branch name we're using already on a branch. Leave it with me!

**Comment by aybarsayan** [comment]
@ChrisChinchilla Sounds good, thank you Chis 😊

**Comment by ChrisChinchilla** [comment]
Closed in favour of https://github.com/KILTprotocol/docs/pull/295

**Pull request closed without merging**
