### PR TITLE
feat: dids readme to the docs page

### PR DESCRIPTION
**Pull request by Dudleyneedham**
## fixes https://github.com/KILTprotocol/ticket/issues/1678

Moving the readme of DID to the docs page

## How to test:

yarn build
yarn start

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)

### CODE REVIEW

**Review by ntn-x2 — CHANGES_REQUESTED** [review]
I would put the section about CTypes right after the DID section, then the sections about claiming, attestations, requesting terms, verification, and delegations, in this order. I would also perhaps like to have one or two lines acting as glue between the different sections, if we change the order between them.

**Comment by Dudleyneedham** [comment]
I have changed the order but went with requesting terms before the attestation.

**Comment by Dudleyneedham** [comment]
I wont add these sentences in this PR. I do agree this should be done, but outside the scope of the ticket and should be created as a new ticket.

**Review by ntn-x2 — APPROVED** [review]
Are the integration tests supposed to pass?

**Comment by Dudleyneedham** [comment]
At the moment, they are failing and have been failing for some time. They do require updating.

**Pull request merged**
