### PR TITLE
instructions on how to fund a test account

### PR DESCRIPTION
**Pull request by drgorb**
## Documentation improvement
I struggled to find out how to get some Kilt tokens into my test account and think it would be useful to have this information on the page

## How to test:
just documentation, no need to run tests

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [x] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [x] I have documented the changes (where applicable)

### CODE REVIEW

**Comment by ntn-x2** [comment]
Hey @drgorb, thanks for your PR! That is definitely good input. I took the liberty to push some changes to your branch, for a couple of reason:

1. We use one-sentence-one-line rule, so we add a new line after every period
2. Code snippets get easily out of sync with the SDK. We have a more-or-less complex system in place where we test snippets and import them as plain text file inside the docs. Given the scope of the section, I think those snippets are out of scope. I anyway left the information about the one command to create the keypair, and the mnemonic itself.

We think this is faster than asking you guys to change the PR to match our style guidelines. Once you acknowledge these changes, I will be more than happy to merge this PR downstream into our codebase 😊

**Comment by drgorb** [comment]
> Hey @drgorb, thanks for your PR! That is definitely good input. I took the liberty to push some changes to your branch, for a couple of reason:
> 
>     1. We use one-sentence-one-line rule, so we add a new line after every period
> 
>     2. Code snippets get easily out of sync with the SDK. We have a more-or-less complex system in place where we test snippets and import them as plain text file inside the docs. Given the scope of the section, I think those snippets are out of scope. I anyway left the information about the one command to create the keypair, and the mnemonic itself.
> 
> 
> We think this is faster than asking you guys to change the PR to match our style guidelines. Once you acknowledge these changes, I will be more than happy to merge this PR downstream into our codebase 😊

Thank you, the information is still useful. I did not think about the code geting out of sync.

**Comment by drgorb** [comment]
if there is documentation on how to create code examples, I'd be glad to add some. There are a few things that I needed to research before I could implement them:

* add a service-endpoint
* create a presentation with selective disclosure
* add or remove a key from a DID

**Comment by ntn-x2** [comment]
> if there is documentation on how to create code examples, I'd be glad to add some

We don't have a documentation on how to integrate code snippets. We have a folder called `code_examples` which act as kind of "integration tests", where files are split into small units, and tested from start to end in a Node script. These files are then imported with the docusaurus `RawLoader` component, which simply imports any file as raw text, and we then show it as a code snippet. In this way, whenever something in the code breaks, we can capture that in the tests, and updating the code automatically updates every snippet where that piece of code is used.

> There are a few things that I needed to research before I could implement them:

add a service-endpoint
create a presentation with selective disclosure
add or remove a key from a DID

I am not entirely sure what you mean here?

**Comment by ntn-x2** [comment]
You can for instance check the full DID creation snippet: https://github.com/KILTprotocol/docs/blob/master/code_examples/sdk_examples/src/core_features/did/04_full_did_simple.ts,

and where it is imported and shown in the docs: https://github.com/KILTprotocol/docs/blob/master/docs/develop/01_sdk/02_cookbook/01_dids/02_full_did_creation.md

**Review by ntn-x2 — APPROVED** [review]

**Pull request merged**
